add_newline = false

[character]
success_symbol = "[❯](bold green)"

[aws]
disabled = true

[gcloud]
disabled = true

[python]
python_binary = ["python3", "python", "python2"]

[cmd_duration]
format = 'in [$duration]($style)'
style = '#abaebe'
