# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Enable for profiling
#zmodload zsh/zprof

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"

ZSH_DISABLE_COMPFIX="true"

# Plugins
plugins=(
  osx
  z
  gradle
  colored-man-pages
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source ~/.zsh_aliases

# Add variables to path.
export PATH="$HOME/.jenv/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
# Add ssh keys
ssh-add -A > /dev/null 2>&1
# Seems to fix % at top of new windows.
unsetopt PROMPT_SP

# Ensure iterm shell integration exists.
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Enable for profiling
#zprof

# Eval statements
eval "$(jenv init -)"
eval "$(starship init zsh)"
